name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name : Coverlet
      uses: b3b00/coverlet-action@master
      with:
        testProject: 'FSharp.DList.Tests/FSharp.DList.Tests.fsproj'
        output: './coverage/lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*'
    - name: Coveralls      
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
